---
- name: Configure dnf-automatic
  community.general.ini_file:
    group: root
    mode: u=rw,g=r,o=r
    option: "{{ item.option }}"
    owner: root
    path: /etc/dnf/automatic.conf
    section: commands
    value: "{{ item.value }}"
  loop:
    - {option: apply_updates, value: true}
    - {option: download_updates, value: true}
    - {option: upgrade_type, value: security}
