---
- name: >-
    Load var file with package names based on the package manager and
    (possibly) OS family- or distribution-specific configuration
  ansible.builtin.include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - >-
          {{ ansible_pkg_mgr }}_{{ ansible_distribution }}_{{
          ansible_distribution_release }}.yml
        - "{{ ansible_pkg_mgr }}_{{ ansible_distribution }}.yml"
        - "{{ ansible_pkg_mgr }}_{{ ansible_os_family }}.yml"
        - "{{ ansible_pkg_mgr }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install packages necessary for automated security updates
  ansible.builtin.package:
    name: "{{ package_names }}"

- name: >-
    Include package manager and (possibly) OS family- or
    distribution-specific configuration tasks
  ansible.builtin.include_tasks:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - >-
          {{ ansible_pkg_mgr }}_{{ ansible_distribution }}_{{
          ansible_distribution_release }}.yml
        - "{{ ansible_pkg_mgr }}_{{ ansible_distribution }}.yml"
        - "{{ ansible_pkg_mgr }}_{{ ansible_os_family }}.yml"
        - "{{ ansible_pkg_mgr }}.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Enable systemd unit that will perform the automated security updates
  ansible.builtin.service:
    name: "{{ service_name }}"
    enabled: true
